# Generated by Django 5.2.6 on 2025-09-23 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('NomCarrera', models.CharField(max_length=45)),
                ('DescCarrera', models.CharField(blank=True, max_length=255, null=True)),
                ('FechCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Carrera',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('NomUser', models.CharField(max_length=45)),
                ('SecondNomUser', models.CharField(blank=True, max_length=45, null=True)),
                ('ApePatUser', models.CharField(max_length=45)),
                ('ApeMatUser', models.CharField(max_length=45)),
                ('UserName', models.CharField(max_length=45, unique=True)),
                ('CorreoUser', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('FotoUser', models.JSONField(blank=True, null=True)),
                ('TipoUser', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesor', 'Profesor'), ('Admin', 'Admin')], max_length=15)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('FechUnido', models.DateTimeField(auto_now_add=True)),
                ('PrivacidadUser', models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default='Publico', max_length=10)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('idCarrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrera')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('idChatbot', models.AutoField(primary_key=True, serialize=False)),
                ('FechInterac', models.DateTimeField(auto_now_add=True)),
                ('UserQuery', models.CharField(max_length=255)),
                ('Response', models.CharField(max_length=255)),
                ('Topic', models.CharField(blank=True, max_length=45, null=True)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Chatbot',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('TituloEvent', models.CharField(max_length=45)),
                ('DescEvent', models.CharField(blank=True, max_length=255, null=True)),
                ('FechEvent', models.DateTimeField()),
                ('LugarEvent', models.CharField(blank=True, max_length=255, null=True)),
                ('Asistencia', models.IntegerField(blank=True, default=0, null=True)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Evento',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('NomGrupo', models.CharField(max_length=45)),
                ('DescGrupo', models.CharField(blank=True, max_length=255, null=True)),
                ('PrivGrupo', models.CharField(choices=[('Publico', 'Publico'), ('Privado', 'Privado')], default='Publico', max_length=10)),
                ('FechCreaGrupo', models.DateTimeField(auto_now_add=True)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='MensajeDirecto',
            fields=[
                ('idMensajeDirecto', models.AutoField(primary_key=True, serialize=False)),
                ('Mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('MediaMensaje', models.JSONField(blank=True, null=True)),
                ('FechMensaje', models.DateTimeField(auto_now_add=True)),
                ('FechUpdateMensaje', models.DateTimeField(blank=True, null=True)),
                ('Leido', models.BooleanField(default=False)),
                ('receiveUser', models.ForeignKey(db_column='receiveUser', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sendUser', models.ForeignKey(db_column='sendUser', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MensajeDirecto',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNot', models.CharField(max_length=45)),
                ('MensajeNot', models.CharField(max_length=255)),
                ('FechEnviado', models.DateTimeField(auto_now_add=True)),
                ('TipoEntrega', models.CharField(choices=[('web', 'web'), ('mail', 'mail')], max_length=4)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('idPost', models.AutoField(primary_key=True, serialize=False)),
                ('TextPost', models.CharField(blank=True, max_length=255, null=True)),
                ('MediaPost', models.JSONField(blank=True, null=True)),
                ('FechCreacPost', models.DateTimeField(auto_now_add=True)),
                ('FechUpdatePost', models.DateTimeField(blank=True, null=True)),
                ('SentimientoScore', models.FloatField(blank=True, null=True)),
                ('SentimientoLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('idGrupo', models.ForeignKey(blank=True, db_column='idGrupo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('idComentario', models.AutoField(primary_key=True, serialize=False)),
                ('TextComentario', models.CharField(max_length=255)),
                ('FechCreacComen', models.DateTimeField(auto_now_add=True)),
                ('FechUpdateComen', models.DateTimeField(blank=True, null=True)),
                ('SentimientoScoreCom', models.FloatField(blank=True, null=True)),
                ('SentimientoLabelCom', models.CharField(blank=True, max_length=255, null=True)),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPost', models.ForeignKey(db_column='idPost', on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('idUsuarioGrupo', models.AutoField(primary_key=True, serialize=False)),
                ('IngresoGrupo', models.DateTimeField(auto_now_add=True)),
                ('Rol', models.CharField(choices=[('Miembro', 'Miembro'), ('Admin', 'Admin')], default='Miembro', max_length=10)),
                ('idGrupo', models.ForeignKey(db_column='idGrupo', on_delete=django.db.models.deletion.CASCADE, to='core.grupo')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsuarioGrupo',
                'unique_together': {('idGrupo', 'idUser')},
            },
        ),
    ]
