# Generated by Django 5.2.6 on 2025-10-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
