# Generated by Django 5.2.6 on 2025-10-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_is_profile_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MediaPost',
            field=models.FileField(blank=True, help_text='Solo imágenes o videos', null=True, upload_to='post_media/'),
        ),
    ]
