# Generated by Django 5.2.6 on 2025-10-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_mediapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MediaPost',
            field=models.FileField(blank=True, help_text='Solo imágenes o videos', null=True, upload_to=''),
        ),
    ]
