# Generated by Django 5.2.6 on 2025-11-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción o biografía del usuario', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil', null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='info_contacto',
            field=models.CharField(blank=True, help_text='Teléfono, email alterno, u otro medio', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_profile_public',
            field=models.BooleanField(default=True, help_text='¿Perfil visible públicamente?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mostrar_contacto',
            field=models.BooleanField(default=False, help_text='¿Mostrar info de contacto?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='show_posts_public',
            field=models.BooleanField(default=True, help_text='¿Mostrar publicaciones del usuario públicamente?'),
        ),
    ]
