# Generated by Django 5.2.6 on 2025-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='ImagenGrupo',
            field=models.ImageField(blank=True, help_text='Imagen de grupo', null=True, upload_to='grupo_images/'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='ReglasGrupo',
            field=models.TextField(blank=True, help_text='Reglas o normas del grupo', null=True),
        ),
    ]
