# Generated by Django 5.2.6 on 2025-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grupo_imagengrupo_grupo_reglasgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogrupo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado')], default='aceptado', max_length=10),
        ),
    ]
