# Generated by Django 5.2.6 on 2025-11-05 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuariogrupo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='Asistencia',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='idUser',
        ),
        migrations.AddField(
            model_name='evento',
            name='Duracion',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='Estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('cancelado', 'Cancelado')], default='vigente', max_length=10),
        ),
        migrations.AddField(
            model_name='evento',
            name='FechCreado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='Modalidad',
            field=models.CharField(blank=True, choices=[('fisica', 'Física'), ('virtual', 'Virtual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='creador',
            field=models.ForeignKey(blank=True, db_column='idCreador', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evento',
            name='DescEvent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='FechEvent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='TituloEvent',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='UsuarioEvento',
            fields=[
                ('idUsuarioEvento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('asistencia', 'Asistencia'), ('inscripcion', 'Inscripción')], default='asistencia', max_length=15)),
                ('FechRegistro', models.DateTimeField(auto_now_add=True)),
                ('idEvento', models.ForeignKey(db_column='idEvento', on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsuarioEvento',
                'unique_together': {('idUser', 'idEvento')},
            },
        ),
    ]
