# Generated by Django 5.2.6 on 2025-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_evento_asistencia_remove_evento_iduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='NomCarrera',
            field=models.CharField(max_length=255),
        ),
    ]
