# Generated by Django 5.2.6 on 2025-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carrera_nomcarrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='Response',
            field=models.CharField(),
        ),
    ]
