# Generated by Django 5.2.6 on 2025-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chatbot_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='UserQuery',
            field=models.CharField(),
        ),
    ]
