# Generated by Django 5.2.6 on 2025-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_chatbot_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='Response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='UserQuery',
            field=models.TextField(),
        ),
    ]
