# Generated by Django 5.2.6 on 2025-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chatbot_response_alter_chatbot_userquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='AlertaIA',
            field=models.BooleanField(default=False, help_text='¿Se disparó alerta automática de IA en este post?'),
        ),
    ]
