# Generated by Django 5.2.6 on 2025-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_post_alertaia'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='AlertaIAChat',
            field=models.BooleanField(default=False, help_text='¿Alerta IA en esta interacción del chatbot?'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='SentimientoLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='SentimientoScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='AlertaIACom',
            field=models.BooleanField(default=False, help_text='¿Alerta IA en este comentario?'),
        ),
        migrations.AddField(
            model_name='mensajedirecto',
            name='AlertaIAMsgDirecto',
            field=models.BooleanField(default=False, help_text='¿Alerta IA en este mensaje directo?'),
        ),
        migrations.AddField(
            model_name='mensajedirecto',
            name='SentimientoLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mensajedirecto',
            name='SentimientoScore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
