# Generated by Django 5.2.6 on 2025-11-06 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_chatbot_alertaiachat_chatbot_sentimientolabel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoApoyo',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('articulo', 'Artículo'), ('video', 'Video'), ('guia', 'Guía'), ('pdf', 'PDF'), ('otro', 'Otro')], max_length=15)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_apoyo/')),
                ('url', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('etiqueta', models.JSONField(blank=True, help_text='Lista de etiquetas/tags', null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('contador_vistas', models.IntegerField(default=0)),
                ('contador_descargas', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RecursoApoyo',
            },
        ),
    ]
